### ISSUE TITLE
AzureAppendBlobAppender only updating logs file after app restart

### ISSUE THREAD

**Issue by AshuBanctec** [Geta/log4net.Azure#1]
Hi Team,

I am using AzureAppendBlobAppender for logging . The issue is that log.xml file is only updated when I restarts the web app(Azure app service) from portal.

**Comment by hurungang** [comment]
try change buffer size and test again?
	
<appender name="AzureAppendBlobAppender" type="log4net.Appender.AzureAppendBlobAppender, log4net.Appender.Azure">
		<bufferSize value="5" />
		...
	  </appender>

**Comment by AshuBanctec** [comment]
@hurungang  I think there is no any configuration or way to specify buffer size, Can you please elaborate what you are refereeing to

**Comment by AshuBanctec** [comment]
@hurungang  I tried changing buffer size explicitly and it worked . Thanks

**Comment by AshuBanctec** [comment]
<appender name="AzureAppendBlobAppender" type="log4net.Appender.AzureAppendBlobAppender, log4net.Appender.Azure">
      <param name="ContainerName" value="testloggingappendblob"/>
      <param name="DirectoryName" value="logs"/>
      
      <param name="ConnectionString" value="XXXX"/>
      <bufferSize value="5" />
      
      <param name="AsText" value="true" />
    </appender>
